title: Level Design Guidelines
description: Proposed structure of Guidelines to learn Level Design that can also be used as a toolkit. 
theme: just-the-docs
baseurl: "/Level-Design-Guidelines"
favicon_ico: /images/favicon.png
url: "https://zephyr-62.github.io"
markdown: kramdown

callouts:
    highlight:
        color: blue
    important:
        title: Important
        color: yellow
    new:
        title: New
        color: green
    note:
        title: Note
        color: purple
    warning:
        title: Warning
        color: red